### ISSUE TITLE
run_scaneagle.py not working 'promotes_outputs' failed to find any matches for 'sweep' and 'taper'

### ISSUE THREAD

**Issue by XinChenCranfield** [mdolab/OpenAeroStruct#367]
## Description
Example run_scaneagle.py not working

It seems that AerostructGeometry attempts to promote 'sweep' and 'taper' as outputs but fail to matches the names (pls see CASE 1 below).

In this example (run_scaneagle.py), these two variables are defined in the "surface" dictionary (line 70 and 74). I am wondering should these varaibles acutually be promoted as inputs rather than outputs (in ...\openaerostruct\integration\aerostruct_groups.py, line 32 - 46)?

        if connect_geom_DVs:
            # If connect_geom_DVs is true, then we promote all of the geometric design variables.
            # If it's false, then we do not promote them, which means that the geometry at each AeroStruct point is independent,
            # and the user can provide different values at each point.
            # This is useful when you want to have morphing DVs, such as twist or span, that are different at each point in a multipoint scheme.
            if "twist_cp" in surface.keys():
                geom_promotes_in.append("twist_cp")
            if "t_over_c_cp" in surface.keys():
                geom_promotes_out.append("t_over_c")
            if "sweep" in surface.keys():
                geom_promotes_out.append("sweep")
            if "taper" in surface.keys():
                geom_promotes_out.append("taper")
            if "mx" in surface.keys():
                geom_promotes_in.append("shape")

if I replace these "geom_promotes_out" with "geom_promotes_in", the prob.setup() will be sucessful, but it starts another error (pls see CASE 2 below).

### Steps to reproduce issue

`python run_scaneagle.py`

### Current behavior

**CASE 1 (without modifying any code)**

Traceback (most recent call last):
  File "d:\Code_and_Testcases\OpenAeroStruct-master\openaerostruct\examples\run_scaneagle.py", line 211, in <module>     
    prob.setup()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\problem.py", line 933, in setup
    model._setup(model_comm, mode, self._metadata)
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\system.py", line 832, in _setup
    self._configure()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\group.py", line 493, in _configure
    subsys._setup_var_data()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\group.py", line 1039, in _setup_var_data        
    var_maps = subsys._get_promotion_maps()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\system.py", line 1996, in _get_promotion_maps   
    resolve(self._var_promotes['output'], ('output',), maps, prom_names)
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\system.py", line 1986, in resolve
    raise RuntimeError(f"{self.msginfo}: '{call}' failed to find any matches for the "
RuntimeError: 'wing.geometry' <class Geometry>: 'promotes_outputs' failed to find any matches for the following names or 
patterns: ['sweep', 'taper'].

**CASE 2 (modifying aerostruct_groups.py)**

D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\utils\general_utils.py:197: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.atleast_1d(value).astype(np.float64)
Traceback (most recent call last):
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\recorders\sqlite_recorder.py", line 403, in startup
    self._abs2meta[name] = real_meta_out[name].copy()
KeyError: 'wing.twist_cp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Code_and_Testcases\OpenAeroStruct-master\openaerostruct\examples\run_scaneagle.py", line 217, in <module>
    prob.run_driver()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\problem.py", line 679, in run_driver
    self.final_setup()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\problem.py", line 1001, in final_setup
    driver._setup_recording()
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\core\driver.py", line 492, in _setup_recording
    self._rec_mgr.startup(self)
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\recorders\recording_manager.py", line 107, in startup
    recorder.startup(recording_requester)
  File "D:\anaconda3\envs\OpenAeroStruct\lib\site-packages\openmdao\recorders\sqlite_recorder.py", line 405, in startup
    self._abs2meta[name] = disc_meta_out[name].copy()
KeyError: 'wing.twist_cp'

### Code versions
- Operating System: Win10
- Python: 3.9.7 64-bit
- OpenMDAO: 3.10.0
- OpenAeroStruct: 2.3.1

**Comment by eytanadler** [comment]
Thanks for bringing this up! I'll make a PR to address this shortly.

You were correct to change sweep and taper to promoting as outputs. The following problem that came up was because wing.twist_cp was both a design variable and constraint in the optimization problem.

**Comment by XinChenCranfield** [comment]
Hi Eytan,

Yes, now I see the problem with wing.twist_cp. Thanks for the help.

BR
Xin
________________________________
