### ISSUE TITLE
Fix the update functionality in plot_wing

### ISSUE THREAD

**Issue by nwu63** [mdolab/OpenAeroStruct#70]
Currently throws
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/home/neil/hg/OpenAeroStruct/openaerostruct/utils/plot_wing.py", line 654, in auto_ref
    self.check_length()
  File "/home/neil/hg/OpenAeroStruct/openaerostruct/utils/plot_wing.py", line 631, in check_length
    self.num_iters = int(db.keys()[-1].split('|')[-1])
IndexError: list index out of range
```

**Comment by johnjasa** [comment]
Fixed by #211
